In [7]:
import pandas as pd
import os
folder = r"C:\Users\Rutuja\.cache\kagglehub\datasets\krishd123\ipl-2026-complete-dataset\versions\13"
for file in os.listdir(folder):

    if file.endswith(".csv"):

        df = pd.read_csv(os.path.join(folder, file))

        print("\n" + "="*60)
        print("FILE:", file)
        print("SHAPE:", df.shape)
        print("\nCOLUMNS:")
        print(df.columns.tolist())

============================================================
FILE: batting_stats.csv
SHAPE: (15, 17)

COLUMNS:
['position', 'batsman', 'team', 'matches', 'innings', 'runs', 'impact', 'average', 'strike_rate', 'not_outs', 'high_score', 'balls_faced', 'hundreds', 'fifties', 'ducks', 'fours', 'sixes']

============================================================
FILE: bowling_stats.csv
SHAPE: (15, 17)

COLUMNS:
['position', 'bowler', 'team', 'matches', 'innings', 'wickets', 'economy', 'impact', 'bbi', 'overs', 'balls', 'dot_balls', 'maiden_overs', 'runs', 'avg', '4wh', '5wh']

============================================================
FILE: deliveries.csv
SHAPE: (17477, 19)

COLUMNS:
['match_no', 'date', 'stage', 'venue', 'batting_team', 'bowling_team', 'innings', 'over', 'striker', 'bowler', 'runs_of_bat', 'extras', 'wide', 'legbyes', 'byes', 'noballs', 'wicket_type', 'player_dismissed', 'fielder']

============================================================
FILE: fielding_stats.csv
SHAPE: (15, 6)

COLUMNS:
['rank', 'player', 'team', 'matches', 'catches', 'cpm']

============================================================
FILE: matches.csv
SHAPE: (39, 23)

COLUMNS:
['match_id', 'date', 'venue', 'team1', 'team2', 'stage', 'toss_winner', 'toss_decision', 'first_ings_score', 'first_ings_wkts', 'second_ings_score', 'second_ings_wkts', 'match_result', 'match_winner', 'wb_runs', 'wb_wickets', 'balls_left', 'player_of_the_match', 'top_scorer', 'highscore', 'best_bowling', 'best_bowling_figure', 'super_over_match']

============================================================
FILE: points_table.csv
SHAPE: (10, 9)

COLUMNS:
['position', 'team', 'matches', 'wins', 'defeats', 'ties', 'abandoned', 'points', 'nrr']

============================================================
FILE: squads.csv
SHAPE: (257, 6)

COLUMNS:
['team_no', 'team_name', 'player', 'nationality', 'role', 'designation']

============================================================
FILE: venues.csv
SHAPE: (12, 5)

COLUMNS:
['venue_stadium', 'city', 'state', 'capacity', 'home_team']

In [9]:
#Step 1: Load All Tables
import pandas as pd
import os

folder = r"C:\Users\Rutuja\.cache\kagglehub\datasets\krishd123\ipl-2026-complete-dataset\versions\13"

matches = pd.read_csv(f"{folder}\\matches.csv")
deliveries = pd.read_csv(f"{folder}\\deliveries.csv")
batting = pd.read_csv(f"{folder}\\batting_stats.csv")
bowling = pd.read_csv(f"{folder}\\bowling_stats.csv")
fielding = pd.read_csv(f"{folder}\\fielding_stats.csv")
points = pd.read_csv(f"{folder}\\points_table.csv")
squads = pd.read_csv(f"{folder}\\squads.csv")
venues = pd.read_csv(f"{folder}\\venues.csv")

In [11]:
#Step 2: Data Quality Check
datasets = {
    "matches": matches,
    "deliveries": deliveries,
    "batting": batting,
    "bowling": bowling,
    "fielding": fielding,
    "points": points,
    "squads": squads,
    "venues": venues
}

for name, df in datasets.items():
    print("\n" + "="*50)
    print(name.upper())

    print("Shape:", df.shape)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicates:")
    print(df.duplicated().sum())

    print("\nData Types:")
    print(df.dtypes)

==================================================
MATCHES
Shape: (39, 23)

Missing Values:
match_id                0
date                    0
venue                   0
team1                   0
team2                   0
stage                   0
toss_winner             0
toss_decision           0
first_ings_score        1
first_ings_wkts         1
second_ings_score       1
second_ings_wkts        1
match_result            0
match_winner            1
wb_runs                24
wb_wickets             17
balls_left              1
player_of_the_match     1
top_scorer              1
highscore               1
best_bowling            1
best_bowling_figure     1
super_over_match        0
dtype: int64

Duplicates:
0

Data Types:
match_id                 int64
date                    object
venue                   object
team1                   object
team2                   object
stage                   object
toss_winner             object
toss_decision           object
first_ings_score       float64
first_ings_wkts        float64
second_ings_score      float64
second_ings_wkts       float64
match_result            object
match_winner            object
wb_runs                float64
wb_wickets             float64
balls_left             float64
player_of_the_match     object
top_scorer              object
highscore              float64
best_bowling            object
best_bowling_figure     object
super_over_match        object
dtype: object

==================================================
DELIVERIES
Shape: (17477, 19)

Missing Values:
match_no                0
date                    0
stage                   0
venue                   0
batting_team            0
bowling_team            0
innings                 0
over                    0
striker                 0
bowler                  0
runs_of_bat             0
extras                  0
wide                    0
legbyes                 0
byes                    0
noballs                 0
wicket_type         16598
player_dismissed    16602
fielder             16791
dtype: int64

Duplicates:
0

Data Types:
match_no              int64
date                 object
stage                object
venue                object
batting_team         object
bowling_team         object
innings               int64
over                float64
striker              object
bowler               object
runs_of_bat           int64
extras                int64
wide                  int64
legbyes               int64
byes                  int64
noballs               int64
wicket_type          object
player_dismissed     object
fielder              object
dtype: object

==================================================
BATTING
Shape: (15, 17)

Missing Values:
position       0
batsman        0
team           0
matches        0
innings        0
runs           0
impact         0
average        0
strike_rate    0
not_outs       0
high_score     0
balls_faced    0
hundreds       0
fifties        0
ducks          0
fours          0
sixes          0
dtype: int64

Duplicates:
0

Data Types:
position         int64
batsman         object
team            object
matches          int64
innings          int64
runs             int64
impact         float64
average        float64
strike_rate    float64
not_outs         int64
high_score       int64
balls_faced      int64
hundreds         int64
fifties          int64
ducks            int64
fours            int64
sixes            int64
dtype: object

==================================================
BOWLING
Shape: (15, 17)

Missing Values:
position        0
bowler          0
team            0
matches         0
innings         0
wickets         0
economy         0
impact          0
bbi             0
overs           0
balls           0
dot_balls       0
maiden_overs    0
runs            0
avg             0
4wh             0
5wh             0
dtype: int64

Duplicates:
0

Data Types:
position          int64
bowler           object
team             object
matches           int64
innings           int64
wickets           int64
economy         float64
impact          float64
bbi              object
overs           float64
balls             int64
dot_balls         int64
maiden_overs      int64
runs              int64
avg             float64
4wh               int64
5wh               int64
dtype: object

==================================================
FIELDING
Shape: (15, 6)

Missing Values:
rank       0
player     0
team       0
matches    0
catches    0
cpm        0
dtype: int64

Duplicates:
0

Data Types:
rank         int64
player      object
team        object
matches      int64
catches      int64
cpm        float64
dtype: object

==================================================
POINTS
Shape: (10, 9)

Missing Values:
position     0
team         0
matches      0
wins         0
defeats      0
ties         0
abandoned    0
points       0
nrr          0
dtype: int64

Duplicates:
0

Data Types:
position       int64
team          object
matches        int64
wins           int64
defeats        int64
ties           int64
abandoned      int64
points         int64
nrr          float64
dtype: object

==================================================
SQUADS
Shape: (257, 6)

Missing Values:
team_no          0
team_name        0
player           0
nationality      0
role             0
designation    247
dtype: int64

Duplicates:
0

Data Types:
team_no         int64
team_name      object
player         object
nationality    object
role           object
designation    object
dtype: object

==================================================
VENUES
Shape: (12, 5)

Missing Values:
venue_stadium    0
city             0
state            0
capacity         0
home_team        0
dtype: int64

Duplicates:
0

Data Types:
venue_stadium    object
city             object
state            object
capacity          int64
home_team        object
dtype: object

In [18]:
matches[['wb_runs','wb_wickets']] = matches[
    ['wb_runs','wb_wickets']
].fillna(0)

In [19]:
matches[matches['first_ings_score'].isnull()]

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
11,12,2026-04-06,"Eden Gardens, Kolkata",KKR,PBKS,League,KKR,Bat,NaN,NaN,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,No

In [20]:
deliveries['is_wicket'] = (
    deliveries['player_dismissed']
    .notna()
    .astype(int)
)

In [21]:
squads['designation'] = squads[
    'designation'
].fillna('Player')

In [22]:
matches['date'] = pd.to_datetime(matches['date'])

deliveries['date'] = pd.to_datetime(
    deliveries['date']
)

In [24]:
deliveries['total_runs'] = (
    deliveries['runs_of_bat']
    + deliveries['extras']
)

In [25]:
deliveries['is_wicket'] = (
    deliveries['player_dismissed']
    .notna()
    .astype(int)
)

In [26]:
matches.to_csv(
    "matches_clean.csv",
    index=False
)

deliveries.to_csv(
    "deliveries_clean.csv",
    index=False
)

squads.to_csv(
    "squads_clean.csv",
    index=False
)

In [27]:
matches.describe(include='all')

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
count,39.000000,39,39,39,39,39,39,39,38.000000,38.000000,...,38,39.000000,39.000000,38.000000,38,38,38.000000,38,38,39
unique,NaN,NaN,11,10,10,1,10,2,NaN,NaN,...,10,NaN,NaN,NaN,34,26,NaN,31,31,2
top,NaN,NaN,"M. Chinnaswamy Stadium, Bangalore",RCB,CSK,League,DC,Bowl,NaN,NaN,...,RCB,NaN,NaN,NaN,Josh Hazlewood,Abhishek Sharma,NaN,Jofra Archer,3--29,No
freq,NaN,NaN,5,5,5,39,7,34,NaN,NaN,...,6,NaN,NaN,NaN,2,3,NaN,3,3,38
mean,20.000000,2026-04-12 14:46:09.230769152,NaN,NaN,NaN,NaN,NaN,NaN,190.526316,6.289474,...,NaN,16.025641,3.256410,10.684211,NaN,NaN,79.447368,NaN,NaN,NaN
min,1.000000,2026-03-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,75.000000,2.000000,...,NaN,0.000000,0.000000,0.000000,NaN,NaN,34.000000,NaN,NaN,NaN
25%,10.500000,2026-04-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,159.750000,4.250000,...,NaN,0.000000,0.000000,0.250000,NaN,NaN,60.750000,NaN,NaN,NaN
50%,20.000000,2026-04-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,197.000000,6.000000,...,NaN,0.000000,4.000000,6.000000,NaN,NaN,77.500000,NaN,NaN,NaN
75%,29.500000,2026-04-19 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,215.000000,8.000000,...,NaN,25.000000,6.000000,12.000000,NaN,NaN,91.750000,NaN,NaN,NaN
max,39.000000,2026-04-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,264.000000,10.000000,...,NaN,103.000000,9.000000,81.000000,NaN,NaN,152.000000,NaN,NaN,NaN
std,11.401754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.394565,2.470451,...,NaN,27.713276,3.101086,15.773918,NaN,NaN,24.521031,NaN,NaN,NaN

In [28]:
deliveries.describe(include='all')

,match_no,date,stage,venue,batting_team,bowling_team,innings,over,striker,bowler,...,extras,wide,legbyes,byes,noballs,wicket_type,player_dismissed,fielder,total_runs,is_wicket
count,17477.000000,17477,17477,17477,17477,17477,17477.000000,17477.000000,17477,17477,...,17477.000000,17477.000000,17477.000000,17477.000000,17477.000000,879,875,686,17477.000000,17477.000000
unique,NaN,NaN,3,13,10,10,NaN,NaN,177,127,...,NaN,NaN,NaN,NaN,NaN,9,147,186,NaN,NaN
top,NaN,NaN,League stage,"Narendra Modi Stadium, Ahmedabad",GT,GT,NaN,NaN,Sai Sudharsan,Kagiso Rabada,...,NaN,NaN,NaN,NaN,NaN,caught,Sai Sudharsan,Jos Buttler,NaN,NaN
freq,NaN,NaN,16502,1851,2043,1988,NaN,NaN,479,400,...,NaN,NaN,NaN,NaN,NaN,660,17,26,NaN,NaN
mean,37.987927,2026-04-27 12:23:26.465640704,NaN,NaN,NaN,NaN,1.480002,9.478646,NaN,NaN,...,0.071122,0.042627,0.010185,0.002403,0.003605,NaN,NaN,NaN,1.567546,0.050066
min,1.000000,2026-03-28 00:00:00,NaN,NaN,NaN,NaN,1.000000,0.100000,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000
25%,20.000000,2026-04-12 00:00:00,NaN,NaN,NaN,NaN,1.000000,4.500000,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000
50%,38.000000,2026-04-26 00:00:00,NaN,NaN,NaN,NaN,1.000000,9.400000,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,0.000000
75%,57.000000,2026-05-13 00:00:00,NaN,NaN,NaN,NaN,2.000000,14.300000,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,2.000000,0.000000
max,74.000000,2026-05-31 00:00:00,NaN,NaN,NaN,NaN,4.000000,19.600000,NaN,NaN,...,5.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN,NaN,7.000000,1.000000
std,21.299799,NaN,NaN,NaN,NaN,NaN,0.500301,5.649094,NaN,NaN,...,0.336309,0.202022,0.100407,0.048964,0.059933,NaN,NaN,NaN,1.827781,0.218087

In [29]:
# Total runs scored on each ball

deliveries['total_runs'] = (
    deliveries['runs_of_bat']
    + deliveries['extras']
)

# Wicket Flag

deliveries['is_wicket'] = (
    deliveries['player_dismissed']
    .notna()
    .astype(int)
)

# Convert dates

matches['date'] = pd.to_datetime(matches['date'])

deliveries['date'] = pd.to_datetime(
    deliveries['date']
)

print("Feature Engineering Completed")

Feature Engineering Completed

In [41]:
matches['date'] = pd.to_datetime(matches['date'])

deliveries['date'] = pd.to_datetime(deliveries['date'])

In [42]:
deliveries['total_runs'] = (
    deliveries['runs_of_bat']
    + deliveries['extras']
)

In [43]:
print("Total Matches Played:",
      matches['match_id'].nunique())

Total Matches Played: 39

In [44]:
#Total Runs In Tournament
print(
    "Total Runs:",
    deliveries['total_runs'].sum()
)

Total Runs: 27396

In [45]:
#Total Wickets
print(
    "Total Wickets:",
    deliveries['is_wicket'].sum()
)

Total Wickets: 875

In [46]:
#Team With Most Wins
matches['match_winner'].value_counts()

match_winner
RCB     6
PBKS    6
SRH     5
RR      4
GT      4
DC      3
LSG     3
CSK     3
MI      2
KKR     2
Name: count, dtype: int64

In [47]:
#Top 10 Run Scorers
top_runs = deliveries.groupby(
    'striker'
)['total_runs'].sum() \
.sort_values(
    ascending=False
).head(10)

print(top_runs)

striker
Vaibhav Sooryavanshi    797
Shubman Gill            772
Sai Sudharsan           760
Virat Kohli             712
Heinrich Klaasen        647
Ishan Kishan            618
Rahul                   614
Abhishek Sharma         608
Mitchell Marsh          597
Jos Buttler             548
Name: total_runs, dtype: int64

In [48]:
#Top 10 Wicket Takers
top_wickets = deliveries[
    deliveries['is_wicket']==1
].groupby('bowler').size() \
.sort_values(
    ascending=False
).head(10)

print(top_wickets)

bowler
Bhuvneshwar Kumar    29
Kagiso Rabada        29
Jofra Archer         29
Anshul Kamboj        24
Eshan Malinga        21
Rashid Khan          21
Rasikh Salam Dar     20
Prince Yadav         20
Mohammed Siraj       20
Kartik Tyagi         19
dtype: int64

In [49]:
#Venue Analysis
venue_matches = matches[
    'venue'
].value_counts()

print(
    venue_matches
)

venue
M. Chinnaswamy Stadium, Bangalore                5
Wankhede Stadium, Mumbai                         4
Ekana Cricket Stadium, Lucknow                   4
Eden Gardens, Kolkata                            4
Arun Jaitley Stadium, Delhi                      4
Narendra Modi Stadium, Ahmedabad                 4
Rajiv Gandhi International Stadium, Hyderabad    4
Barsapara Stadium, Guwahati                      3
New PCA Cricket Stadium, Mullanpur               3
MA Chidambaram Stadium, Chennai                  3
Sawai Mansingh Stadium, Jaipur                   1
Name: count, dtype: int64

In [50]:
#Toss Decision Analysis
matches[
    'toss_decision'
].value_counts()

toss_decision
Bowl    34
Bat      5
Name: count, dtype: int64

In [51]:
#point Table 
points.sort_values(
    by='points',
    ascending=False
)

,position,team,matches,wins,defeats,ties,abandoned,points,nrr
0,1,Punjab Kings,7,6,0,0,1,13,1.333
1,2,Royal Challengers Bengaluru,8,6,2,0,0,12,1.919
2,3,Sunrisers Hyderabad,8,5,3,0,0,10,0.815
3,4,Rajasthan Royals,8,5,3,0,0,10,0.602
4,5,Gujarat Titans,8,4,4,0,0,8,-0.475
5,6,Chennai Super Kings,8,3,5,0,0,6,-0.121
6,7,Delhi Capitals,8,3,5,0,0,6,-1.060
7,8,Kolkata Knight Riders,8,2,5,0,1,5,0.751
8,9,Mumbai Indians,7,2,5,0,0,4,-0.736
9,10,Lucknow Super Giants,8,2,6,0,0,4,-1.106

In [52]:
#Most Sixes
batting[
['batsman','sixes']
].sort_values(
    by='sixes',
    ascending=False
).head(10)

                 batsman  sixes
2   Vaibhav Sooryavanshi     32
0        Abhishek Sharma     28
13         Priyansh Arya     25
10          Shreyas Iyer     21
1               KL Rahul     19
6          Sai Sudarshan     17
7           Ishan Kishan     16
9      Prabhsimran Singh     16
14      Devdutt Padikkal     16
8           Sanju Samson     15

In [53]:
#Most Fours
batting[
['batsman','fours']
].sort_values(
    by='fours',
    ascending=False
).head(10)

                 batsman  fours
3            Virat Kohli     37
0        Abhishek Sharma     36
1               KL Rahul     36
7           Ishan Kishan     35
8           Sanju Samson     33
6          Sai Sudarshan     32
2   Vaibhav Sooryavanshi     31
9      Prabhsimran Singh     31
11           Jos Buttler     31
5           Shubman Gill     30

In [54]:
!pip install sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in c:\users\rutuja\appdata\roaming\python\python313\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [55]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:local123@localhost:5432/ipl_analysis"
)

print("Connected Successfully")

Connected Successfully

In [56]:
import pandas as pd

pd.read_sql(
    "SELECT version();",
    engine
)

                                             version
0  PostgreSQL 18.4 on x86_64-windows, compiled by...

In [57]:
matches.to_sql(
    "matches",
    engine,
    if_exists="replace",
    index=False
)

39

In [58]:
deliveries.to_sql(
    "deliveries",
    engine,
    if_exists="replace",
    index=False
)

477

In [59]:
batting.to_sql(
    "batting_stats",
    engine,
    if_exists="replace",
    index=False
)

15

In [60]:
bowling.to_sql(
    "bowling_stats",
    engine,
    if_exists="replace",
    index=False
)

15

In [61]:
fielding.to_sql(
    "fielding_stats",
    engine,
    if_exists="replace",
    index=False
)

15

In [62]:
squads.to_sql(
    "squads",
    engine,
    if_exists="replace",
    index=False
)

257

In [63]:
venues.to_sql(
    "venues",
    engine,
    if_exists="replace",
    index=False
)

12

In [67]:
points.to_sql(
    "points_table",
    engine,
    if_exists="replace",
    index=False
)

10